learning_templates/My_app/urls.py
from django.urls import path 
from My_app import views

app_name = 'My_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path , include
from My_app import views


urlpatterns = [
    path('', views.index, name='index'),
    path('My_app/', include('My_app.urls')),
    path('admin/', admin.site.urls, name='index')
    
]

learning_templates/My_app/models.py
# Create your models here.

learning_templates/My_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render (request,'My_app/index.html')

def other(request):
    return render (request,'My_app/other.html')

def relative(request):
    return render (request,'My_app/relative.html')

learning_templates/templates/My_app/index.html
<!DOCTYPE html>

{% extends "My_app/my.html" %}

  {% block body_block %}

   <h1> Welcome to Index! </h1>
   <h2> This is Index.html showing</h2>
  {% endblock %} 
    

learning_templates/templates/My_app/my.html
<!DOCTYPE html>
<html>
    <head>
        <title>   </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class= "nav navbar-nav"> 
                    <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                    <li><a class="navbar-link" hre="{% url 'admin:index' %}">ADMIN</a></li>
                    <li><a class="navbar-link" href="{% url 'My_app:other' %}">OTHER</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">


            {% block body_block %}


            {% endblock %}




        </div>
     </body>





</html>

learning_templates/templates/My_app/other.html
<!DOCTYPE html>

{% extends "My_app/my.html" %}

  {% block body_block %}

   <h1> Welcome to other! </h1>
   <h2> This is Example of template inhertance</h2>
  {% endblock %} 
    

learning_templates/templates/My_app/relative.html
<html>
<head>

    <title>     </title>

</head>
<body>
    <h1> Welcome to relative templates </h1>
    <a href= "other" > THE OTHER PAGE </a>
    <a href="{ % url 'admin:index' % }" > LINK TO ADMIN </a>


</body>
</html>